### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by arminvoid** [atvanguard/dada#6]
**Art Buyer**
- [x] Sees an endless feed of art up for sale like https://dada.nyc/artgallery
```
GET /listing

[
    {
        "id": "1969826650673688744_10732810682",
        "caption": "Snow babies",
        "url": "123.com",
        "owner": "0x60697A2711fCd77bA434faF04588f9b20fc96A3c"
    },
    {
        "id": "1969648271227895297_10732810682",
        "caption": "Cycle yo",
        "url": "456.com",
        "owner": "0x60697A2711fCd77bA434faF04588f9b20fc96A3c"
    }
]
```
- [x] Approve button, with currency select list - here the user approves our contract to move tokens on their behalf
- [x] When the buyer clicks on an art, a widget where they select the currency and signs an order (this is the bid)

**Art Creator**
- [x] `Sign up with instagram` button - links to `/account/authorize_user`
    - [x] saves a token (received from server) to browser localStorage
- Profile page - retrieves data from `/account/me`
- [x] `Connect Metamask button` - will have the address signed and send sig to `/account/linkAddress`
- [x]  On the profile page, user will see their art. A functionality to select multiple arts and then press `import button` that calls `/account/import`
